#!/bin/sh
# postinst script for brewable
#

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package

# source debconf library
. /usr/share/debconf/confmodule

case "$1" in

  configure)
    update-rc.d brewable defaults
    grep "^dtoverlay=w1-gpio" /boot/config.txt || \
	sed -i -e '$a\\n# OneWire temperature sensor\ndtoverlay=w1-gpio,gpiopin=4' /boot/config.txt
    grep "^dtparam=i2c_arm=off" /boot/config.txt && \
	sed -i -e 's:dtparam=i2c_arm=off:dtparam=i2c_arm=on:' /boot/config.txt || \
        grep "^dtparam=i2c_arm=on" /boot/config.txt || \
	sed -i -e '$a\\n# i2c for Seeed Relay\ndtparam=i2c_arm=on' /boot/config.txt
    exit 0
  ;;

  abort-upgrade|abort-remove|abort-deconfigure)
    exit 0
  ;;

  *)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 1
  ;;

esac

exit 0
