#!/bin/sh

# Copyright (c) 2016 Christoph Willing (Brisbane, Australia)
# All rights reserved.
#
# Author: Christoph Willing, 2016
#
# /etc/init.d/brewable

### BEGIN INIT INFO
# Provides:          brewable
# Required-Start:    $network
# Required-Stop:
# Default-Start:     3 5
# Default-Stop:      0 1 2 6
# Short-Description: brewable temperature controller daemon
# Description:       The brewable daemon starts a tornado web server
#	enabling remote browser control of a temperature control system.
#	We want it to be active in runlevels 3 and 5,
#	as these are the runlevels with the network available.
### END INIT INFO


# Check for config file
BREWABLE_CONFIG=/etc/default/brewable
test -r $BREWABLE_CONFIG || { echo "$BREWABLE_CONFIG not found";
	if [ "$1" = "stop" ]; then exit 0;
	else exit 5; fi; }

# Read config
. $BREWABLE_CONFIG

# Check for server file
BREWABLE_SERVER=$BREWABLE_RUN_DIR/server.py
test -x $BREWABLE_SERVER || { echo "$BREWABLE_SERVER not installed";
	if [ "$1" = "stop" ]; then exit 0;
	else exit 5; fi; }

brewable_start () {
    echo "Starting brewable"
    cd $BREWABLE_RUN_DIR
    su -c $BREWABLE_SERVER $BREWABLE_USER &
}

brewable_stop () {
    echo "Stopping brewable"
    ps -ef \
        | grep -v grep \
        | grep "python $BREWABLE_SERVER" \
        | awk '{print $2}' \
        | xargs kill 1>/dev/null 2>/dev/null
}

case "$1" in
    start)
        brewable_start
        ;;
    stop)
        brewable_stop
        ;;
    restart)
        brewable_stop
        sleep 1
        brewable_start
        ;;
    *)
        echo "Usage: /etc/init.d/brewable start|stop|restart"
        exit 1
        ;;
esac

exit 0

# ex:set ai shiftwidth=4 inputtab=spaces smarttab noautotab:
